# -*- coding: utf-8 -*-
"""graphs and linear regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_GmePiZV7T-rhdohPcNGWVB1poWi4WNq

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. Scatter and Line Plots
 
 2. Boxplot

 3. Pie Chart and Bell Curve

 4. Simple Linear Regression

---

#### Activity 1: Create Pandas DataFrame

Create a Pandas DataFrame for the **Weight-Height** dataset using the below link. This dataset has 10,000 rows and provides the weight, height and gender of the person.

  **Source:** https://www.kaggle.com/majidarif17/weight-and-heightcsv

  **Dataset Link:**https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/weight-height/weight-height.csv

Also, print the first five rows of the dataset. Check for null values and treat them accordingly.

---
"""

# Import modules
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df=pd.read_csv('https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/weight-height/weight-height.csv')
df.head()

# Check if there are any null values. If any column has null values, treat them accordingly
df.isna().sum()

# Get the descriptive statistics summary of the DataFrame

df.describe()

"""---

#### Activity 2: Create Pie Chart

Find out whether the dataset is balanced i.e., whether the dataset has an equal number of Male and Female. For this, create a pie chart with labels.
"""



# Check if the dataset is balanced or not using pie chart for 'Gender'
labels=df['Gender'].unique()
sizes=df['Gender'].value_counts()*100/df.shape[0]
plt.figure(dpi=100)
#df['Gender'].head()
plt.pie(sizes,labels=labels,autopct='%1.1f%%')
plt.title('Number of Male and female')
plt.show()

"""**Q:** Is there an equal distribution of males and females in the above dataset?

**A:** Yes

---

#### Activity 3: Boxplot for Heights and Weights

Create boxplots to show the distribution of weight and height in males and females.
"""

# Create a boxplot for gender-wise variation in heights.

plt.figure(figsize=[15,5])
sns.boxplot(df['Gender'],df['Height'])
plt.show()

# Create a boxplot for gender-wise variation in weights.

plt.figure(figsize=[15,5])
sns.boxplot(df['Gender'],df['Weight'])
plt.show()

"""**Q:** What can be concluded from the above boxplot, who is taller and heavier in weight, Male or Female?

**A:** 
Male

----

#### Activity 4: Create Scatter Plot and Regression Plot

Create a scatter plot and a regression plot to identify if there exists any relationship between height and weight of a person.
"""

# Create a scatter plot with height on X-axis and weight on Y-axis 


plt.figure(figsize=[15,5])
plt.scatter(df['Height'],df['Weight'])
plt.xlabel("Height")
plt.ylabel('Weight')
plt.title("Height VS Weight")
plt.show()

# Create a regression plot for height and weight

plt.figure(figsize=[15,5])
sns.regplot(df['Height'],df['Weight'],color='green')
plt.xlabel("Height")
plt.ylabel('Weight')
plt.title("Height VS Weight")
plt.show()

"""**Q:** Is there exists a positive linear relationship between heights and weights of individuals?

**A:** Yes

"""